---
name: CI
on:
  push:
    branches:
      - main
jobs:
  build_and_upload:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './build/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
